[package]
name = "sqlite3_ext"
version = "0.1.0"
edition = "2021"

[workspace]
members = [ "sqlite3_ext_macro" ]

[features]
static = [ "dep:rusqlite", "dep:libsqlite3-sys" ]
static_modern = [ "static", "rusqlite?/modern_sqlite" ]

[dependencies]
bigdecimal = { version = "0.3.0", optional = true }
libsqlite3-sys = { version = "0.24.0", optional = true }
rusqlite = { version = "0.27.0", optional = true }
sealed = "0.4.0"
sqlite3_ext_macro = { path = "sqlite3_ext_macro" }

[dev-dependencies]
nom = "7.1.1"
pretty_assertions = "1.2.1"
indoc = "1.0"

[build-dependencies]
proc-macro2 = "1.0"
which = "4.2.5"
syn = { version = "1.0", features = [ "parsing", "full" ] }
quote = "1.0"

[[test]]
name = "read_only"
required-features = [ "static" ]

[[test]]
name = "update"
required-features = [ "static" ]

[[example]]
name = "generate_series"
crate-type = [ "staticlib", "cdylib" ]
test = true

[[example]]
name = "vtablog"
crate-type = [ "staticlib", "cdylib" ]
test = true

[[example]]
name = "decimal"
required-features = [ "bigdecimal" ]
crate-type = [ "staticlib", "cdylib" ]
test = true
