[package]
name = "crdb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib","staticlib"]

[dependencies]
libsqlite3-sys = "0.24.2"
rusqlite = "0.27.0"
