[package]
name = "crdb"
version = "0.1.0"
edition = "2021"

[workspace]
members = [ "sqlite3_ext" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = [ "cdylib", "staticlib" ]

[dependencies]
sqlite3_ext = { path = "sqlite3_ext" }

[build-dependencies]
proc-macro2 = "1.0.39"
which = "4.2.5"
syn = { version = "1.0.96", features = [ "parsing", "full" ] }
quote = "1.0.18"
